import 'package:flutter/material.dart';
import 'expense.dart';

/// Types of insights the service can generate.
enum InsightType {
  /// Unusual spending (>2x normal)
  anomaly,

  /// On pace to exceed budget
  warning,

  /// Significant change vs last month (>25%)
  comparison,

  /// Positive milestone (lowest in X months)
  achievement,

  /// Recurring pattern detected
  pattern,
}

/// Priority level for insights, determines display order.
enum InsightPriority { high, medium, low }

/// Extension to provide icons for insight types.
extension InsightTypeExtension on InsightType {
  /// Returns a Material icon for the insight type.
  /// Following Ledgerify Design Language - rounded, solid, minimal icons.
  IconData get icon {
    switch (this) {
      case InsightType.anomaly:
        return Icons.warning_amber_rounded;
      case InsightType.warning:
        return Icons.trending_up_rounded;
      case InsightType.comparison:
        return Icons.compare_arrows_rounded;
      case InsightType.achievement:
        return Icons.star_rounded;
      case InsightType.pattern:
        return Icons.repeat_rounded;
    }
  }
}

/// Represents an automatically generated insight about spending patterns.
///
/// Insights are generated by analyzing expense data and surfacing
/// interesting patterns, anomalies, or achievements to the user.
///
/// Follows Quiet Finance principles:
/// - Factual, not emotional
/// - No gamification language
/// - Format: "Category up/down X% — reason"
class SmartInsight {
  /// Unique identifier for this insight.
  final String id;

  /// The type of insight (anomaly, warning, comparison, etc.).
  final InsightType type;

  /// Priority determines display order (high first).
  final InsightPriority priority;

  /// Short title: "Food up 34%"
  final String title;

  /// Detailed description: "12 Swiggy orders (₹4,200)"
  final String description;

  /// Icon to display with the insight.
  final IconData icon;

  /// Related amount if applicable.
  final double? amount;

  /// Related category name (display name) if applicable.
  final String? categoryName;

  /// Related category if applicable.
  final ExpenseCategory? category;

  /// IDs of related transactions for drill-down navigation.
  final List<String>? relatedTransactionIds;

  /// When this insight was generated.
  final DateTime generatedAt;

  SmartInsight({
    required this.id,
    required this.type,
    required this.priority,
    required this.title,
    required this.description,
    IconData? icon,
    this.amount,
    this.categoryName,
    this.category,
    this.relatedTransactionIds,
    DateTime? generatedAt,
  })  : icon = icon ?? type.icon,
        generatedAt = generatedAt ?? DateTime.now();

  /// Creates a copy of this insight with optional field overrides.
  SmartInsight copyWith({
    String? id,
    InsightType? type,
    InsightPriority? priority,
    String? title,
    String? description,
    IconData? icon,
    double? amount,
    String? categoryName,
    ExpenseCategory? category,
    List<String>? relatedTransactionIds,
    DateTime? generatedAt,
    bool clearAmount = false,
    bool clearCategoryName = false,
    bool clearCategory = false,
    bool clearRelatedTransactionIds = false,
  }) {
    return SmartInsight(
      id: id ?? this.id,
      type: type ?? this.type,
      priority: priority ?? this.priority,
      title: title ?? this.title,
      description: description ?? this.description,
      icon: icon ?? this.icon,
      amount: clearAmount ? null : (amount ?? this.amount),
      categoryName:
          clearCategoryName ? null : (categoryName ?? this.categoryName),
      category: clearCategory ? null : (category ?? this.category),
      relatedTransactionIds: clearRelatedTransactionIds
          ? null
          : (relatedTransactionIds ?? this.relatedTransactionIds),
      generatedAt: generatedAt ?? this.generatedAt,
    );
  }

  /// Converts the insight to a JSON map.
  /// Useful for debugging or future export features.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'type': type.name,
      'priority': priority.name,
      'title': title,
      'description': description,
      'amount': amount,
      'categoryName': categoryName,
      'category': category?.name,
      'relatedTransactionIds': relatedTransactionIds,
      'generatedAt': generatedAt.toIso8601String(),
    };
  }

  @override
  String toString() {
    return 'SmartInsight(id: $id, type: ${type.name}, priority: ${priority.name}, title: $title)';
  }
}
